services:
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass test_pass
    volumes:
      - ./out/redis_data:/data
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "--no-auth-warning",
          "-a",
          "test_pass",
          "PING",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
